### PR TITLE
name change of pysal_core to libpysal

### PR DESCRIPTION
**Pull request by sjsrey**

### CODE REVIEW

**Comment by ljwolf** [comment]
I will cherry pick this into #3

**Comment by ljwolf** [comment]
Oh, rebase (hopefully) works too

**Comment by sjsrey** [comment]
Sorry about that. Hopefully the rebase works

**Comment by ljwolf** [comment]
yeah... will look into it. This is definitely the critical point of the development bootstrapping that needs to be ironed out before doing another submodule :frowning_face: 

I'm not sure why the `pip install git+X` isn't providing libpysal to the environment. Will look into it.

**Comment by ljwolf** [comment]
```
git clone https://github.com/pysal/libpysal && pip install -e ./libpysal
```
works, but 
```
pip install git+https://github.com/pysal/libpysal.git
```
installs a blank package, locally or on travis.

**Pull request merged**
