### PR TITLE
[WIP]

### PR DESCRIPTION
**Pull request by ljwolf**

### CODE REVIEW

**Comment by ljwolf** [comment]
These tests will need to re-run when pysal_core/#11 gets merged.

**Comment by sjsrey** [comment]
@ljwolf do we need to rename `pysal/pysal_core` to `pysal/libpysal` or should we simply create a new repos `pysal/libpysal` and get things working? once we are rolling we can delete `pysal/pysal_core'.

**Comment by shaohu** [comment]
Have the same question. @sjsrey @ljwolf  The travis build didn't pass because the repo "https://github.com/pysal/libpysal.git" in configure file does exist. Once this problem is fixed, I will begin updating this pysal_points repo.

**Comment by ljwolf** [comment]
@sjsrey I would create libpysal as a copy of pysal_core, re-run travis on this to see if it passes, and then delete pysal_core when we're sure libpysal is correct. 

This would break the forks of pysal_core that currently exist, but those shouldn't be too far from current anyway.

**Comment by ljwolf** [comment]
And yes, this won't pass unless `git@github.com:pysal/libpysal.git` exists.

**Pull request merged**
